src/events/urls.py
from django.conf.urls import url

from views import calendarpage, jsonsearch, fcdragmodify, EventManager, event_view

event_manager = EventManager.as_view()
urlpatterns = [
  url(r'^$', calendarpage, name='events'),
  url(r'^json/', jsonsearch, name='jsonsearch'),
  url(r'^modify/', fcdragmodify, name='fcdragmodify'),

  url(r'^new/', event_manager, name='newevent'),
  url(r'^(?P<eventid>\d+)/edit/', event_manager, name='editevent'),
  url(r'^recurring/(?P<eventid>\d+)/edit/(?:orig-(?P<originaleventid>\d+)/)?', event_manager, {'editingregularevent': False}, name='editrecurringevent'),

  # Must be last...
  url(r'^(?P<eventid>\d+)/', event_view, name='viewevent'),
]

src/events/models.py
from datetime import date, timedelta

from django.db import models
from django.contrib.sites.models import Site
from django.core.validators import MinValueValidator

from clubdata.models import Club





def range_date_inclusive(start_date, end_date):
  for n in range((end_date - start_date).days+1):
    yield start_date + timedelta(n)

def num_days_in_month(d):
  dmonth = d.month
  if dmonth == 12:
    return 31
  else:
    return (d.replace(month=dmonth+1, day=1) - timedelta(days=1)).day

def last_day_in_month(d):
  dmonth = d.month
  if dmonth == 12:
    return d.replace(day=31)
  else:
    return d.replace(month=dmonth+1, day=1) - timedelta(days=1)

def decode_weekly_criteria(criteria):
  c = criteria.split(",")
  dow_possible = ('mo','tu','we','th','fr','sa','su')
  dow = [False,False,False,False,False,False,False]
  for x in c: dow[dow_possible.index(x)] = True
  return dow

def decode_monthly_criteria(criteria):
  c = criteria.split(",")
  specificdays = []
  daystocalculate = []
  dow_possible = ('mo','tu','we','th','fr','sa','su')
  for x in c:
    if x.isdigit():
      # Specific numbered day (same every month)
      specificdays.append(int(x))
    else:
      # A code to represent a day. We'll convert from strings to integers for later.
      if x == 'last':
        # Last day of the month (must be calculated later)
        daystocalculate.append( (99, -1) )
      else:
        y,z = x.split("-")
        if y == 'last':
          # Last DOW of the month (must be calculated later)
          daystocalculate.append( (99, dow_possible.index(z)) )
        else:
          # Specified DOW of the month (must be calculated later)
          daystocalculate.append( (int(y), dow_possible.index(z)) )
  return specificdays,daystocalculate





class RecurringEvent(models.Model):
  DAILY = 100
  WEEKLY = 200
  MONTHLY = 300
  rule_type_choices = (
    (DAILY, 'Daily'),
    (WEEKLY, 'Weekly'),
    (MONTHLY, 'Monthly'),
  )

  id                    = models.AutoField(
                            primary_key=True)

  # Range
  starts_on             = models.DateField('Starts on')
  ends_on               = models.DateField('Ends on')

  # Rule
  rule_type             = models.IntegerField('Recurring rule',
                            choices=rule_type_choices,
                            default=WEEKLY)
  repeat_each           = models.IntegerField('Repeat each',
                            default=1,
                            validators=[MinValueValidator(1)])
  criteria              = models.CharField('Criteria',
                            max_length=200,
                            null=True,  # Blank is stored as Null
                            blank=True) # Field is optional

  class Meta:
    verbose_name = 'Recurring Event'
    verbose_name_plural = 'Recurring Events'

  def __unicode__(self): #Python 3.3 is __str__
    rt = self.rule_type
    for t in self.rule_type_choices:
      if t[0] == rt:
        rt = t[1]
        break
    return "%s Event, %s to %s, Criteria=\"%s\"" % (rt, self.starts_on, self.ends_on, self.criteria)

  def dates_per_rule_iter(self):
    if self.rule_type == self.WEEKLY:
      # criteria = Must be a comma-separated list of lowercase 2-letter abbreviations for the days
      #   of the week. Ex: mo,we,fr,su
      # repeat_each = If this is 2, then every other week will be skipped. If it is 3,
      #   then two weeks will be skipped between each filled week. etc...

      # Deconstruct the criteria
      criteria = decode_weekly_criteria(self.criteria)

      # Generate a list of dates that match
      if self.repeat_each == 1:
        # If repeat_each is 1, then our calculation is much simpler
        for x in range_date_inclusive(self.starts_on, self.ends_on):
          if criteria[x.weekday()]: yield x
      else:
        # Special handling because we're not doing every week
        r = 2 # Set this to 2 so the first iteration will set it to 1
        dow_begin = self.starts_on.weekday()
        for x in range_date_inclusive(self.starts_on, self.ends_on):
          wd = x.weekday()
          if wd == dow_begin:
            # It's the beginning of a new week (rather than assuming the user considers Monday to be
            #   the first day of the week, we use the DOW of the start of the range for this purpose.
            if r == 1:
              # Reset the counter
              r = self.repeat_each
            else:
              # Decrease the counter
              r -= 1
          if r == 1:
            # If counter is 1, then this week should be included
            if criteria[wd]: yield x

    elif self.rule_type == self.MONTHLY:
      # criteria = Must be a comma-separated list of the following types of codes:
      #   * 1,2,3,4, etc                specific days of the month
      #   * 1-mo, 3-fr, last-we, etc    first Monday, third Friday, last Wednesday, etc.
      #   * last                        last day of the month
      # repeat_each = If this is 2, then every other month will be skipped. If it is 3, then two
      #   months will be skipped between each filled month. etc...

      # Deconstruct the criteria
      specificdays,daystocalculate = decode_monthly_criteria(self.criteria)

      # Generate a list of dates that match
      calcdays = None
      oneday = timedelta(days=1)
      r = 2 # Set this to 2 so the first iteration will set it to 1
      for x in range_date_inclusive(self.starts_on, self.ends_on):
        xday = x.day
        if (xday == 1) or (calcdays is None):
          # It's the first day of the month (or first iteration of this loop)
          if r == 1:
            # Reset the counter
            r = self.repeat_each
          else:
            # Decrease the counter
            r -= 1
          if r == 1:  # Putting this within the above 'else' will malfunction if repeat_each is 1
            # Since this month is included, we must turn those vague days into specific numbered days
            #   for this current month (each month is different, so they couldn't have been calculated earlier.
            calcdays = []
            for y in daystocalculate:
              if y[0] == 99:
                if y[1] == -1:
                  # Calculate the last day of the month
                  calcdays.append(num_days_in_month(x))
                else:
                  # Calculate the last DOW of the month
                  end_date = last_day_in_month(x)
                  for z in range(end_date.day):
                    d = end_date - timedelta(z)
                    if d.weekday() == y[1]:
                      calcdays.append(d.day)
                      break
              else:
                # Calculate the specified DOW of the month
                start_date = date(x.year, x.month, 1)
                found_count = 0
                for z in range(num_days_in_month(start_date)):
                  d = start_date + timedelta(z)
                  if d.weekday() == y[1]:
                    found_count += 1
                    if found_count == y[0]:
                      calcdays.append(z+1)
                      break
            print(calcdays)
        # Check if this month is included (not a skipped month per the repeat_each rule)
        if r == 1:
          if (xday in specificdays) or (xday in calcdays):
            # Assuming the daystocalculate have been calculated (above), simply check if the day is
            #   in one of the two lists
            yield x

    elif self.rule_type == self.DAILY:
      # criteria = Not used
      # repeat_each = If this is 2, then every other day will be skipped. If it is 3, only every
      #   third day will be chosen. etc...

      # Generate a list of dates that match
      if self.repeat_each == 1:
        # If repeat_each is 1, then our calculation is much simpler
        for x in range_date_inclusive(self.starts_on, self.ends_on):
          yield x
      else:
        # Use the repeat value.
        r = self.repeat_each # Include the first day of the range, and then start counting from there
        for x in range_date_inclusive(self.starts_on, self.ends_on):
          if r == self.repeat_each:
            yield x
            r = 1
          else:
            r += 1





class CustomEventManager(models.Manager):
  # Custom manager to show only the items that either
  #   (a) belong to the current Club, or
  #   (b) belong to no Club
  use_in_migrations = True

  current_club_id = None

  def _get_current_club_id(self):
    if not self.current_club_id:
      current_site = Site.objects.get_current()
      if current_site.has_club:
        self.current_club_id = current_site.club.id
    return self.current_club_id

  def get_queryset(self):
    return super(CustomEventManager, self).get_queryset().filter(
      models.Q(club=self._get_current_club_id()) | models.Q(club=None))

class Event(models.Model):
  id                    = models.AutoField(
                            primary_key=True)
  club                  = models.ForeignKey(Club, verbose_name='Specific to club',
                            help_text='Only the specified club will show the event on their calendar. If none, event will show on calendars of all clubs.',
                            null=True,  # Blank is stored as Null
                            blank=True, # Field is optional
                            on_delete=models.SET_NULL)  # Deleting a club will leave all associated events behind as global events
  title                 = models.CharField('Title',
                            blank=True, # Field is optional
                            max_length=200)
  start                 = models.DateTimeField('Start date/time')
  duration              = models.DurationField('Duration')
  all_day               = models.BooleanField('All day event?',
                            default=False)
  recurring             = models.ForeignKey(RecurringEvent, verbose_name='Belongs to recurring group',

src/events/forms.py
import re
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils import six

from .models import Event, RecurringEvent

re_weekly = re.compile(r'^((mo|tu|we|th|fr|sa|su),)+$')
re_monthly = re.compile(r'^([1-3][0-9],|[1-9],|last,|(([1-5]|last)-(mo|tu|we|th|fr|sa|su)),)+$')


def duration_string(duration):
  """
  This is originally taken from django.utils.duration, but modified to not show seconds by default,
  and to show the "day" or "days" text
  """
  days = duration.days
  seconds = duration.seconds
  microseconds = duration.microseconds

  minutes = seconds // 60
  seconds = seconds % 60

  hours = minutes // 60
  minutes = minutes % 60

  if days:
    if days == 1:
      string = '{} day'.format(days)
    else:
      string = '{} days'.format(days)
  else:
    string = None

  if hours or minutes or seconds or microseconds:
    if string is None:
      string = '{:02d}:{:02d}'.format(hours, minutes)
    else:
      string += ', {:02d}:{:02d}'.format(hours, minutes)
    if seconds:
      string += ':{:02d}'.format(seconds)
    if microseconds:
      string += '.{:06d}'.format(microseconds)

  return string

simple_duration_re = re.compile(
  r'^'
  r'(?:(?P<days>\d+) (days?(?:, )?)?)?'
  r'(?:(?P<hours>\d{1,2}):(?P<minutes>\d{2}))?'
  r'$'
)
def parse_duration(value):
  """
  This is originally taken from django.utils.dateparse, but modified to not allow seconds or microseconds
  """
  match = simple_duration_re.match(value)
  if match:
    kw = match.groupdict()
    kw = {k: float(v) for k, v in six.iteritems(kw) if v is not None}
    return datetime.timedelta(**kw)

class SimpleDurationField(forms.DurationField):
  """
  DurationField modified to use 'duration_string', 'parse_duration', and 'simple_duration_re' from
  above instead of the ones Django provide
  """
  def prepare_value(self, value):
    if isinstance(value, datetime.timedelta):
      return duration_string(value)
    return value

  def to_python(self, value):
    if value in self.empty_values:
      return None
    if isinstance(value, datetime.timedelta):
      return value
    value = parse_duration(value)
    if value is None:
      raise ValidationError(self.error_messages['invalid'], code='invalid')
    return value






class EventEditForm(forms.Form):
  """
  Form for creating and editing both regular and recurring events. This is not a ModelForm, as we need
  special handling for most of the fields.
  """

  NORECURRING = 0
  criteria_help_texts = (
    (RecurringEvent.DAILY, 'Criteria is not used for daily events.'),
    (RecurringEvent.WEEKLY, 'Comma-separated list of 2-letter abbreviations. Example: <i>Mo,We,Fr,Su</i>'),
    (RecurringEvent.MONTHLY, 'Comma-separated list of codes. Example:<i>1,7,2-Mo,26,Last-Fr,Last</i>'
      '<ul>'
        '<li>Days of the month: 1, 17, 24, etc.</li>'
        '<li>Specific instance of a day-of-week: 3-Mo, 1-Fr, Last-Sa, etc.</li>'
        '<li>Last day of the month: Last</li>'
      '</ul>'),
  )

  event_type            = forms.TypedChoiceField(label='Event type',
                            coerce=int,
                            empty_value=NORECURRING,
                            required=False)
  start_date            = forms.DateField(label='<span class="hide-if-onetime">Start of range</span><span class="show-if-onetime">Date</span>',
                            required=False,
                            widget=forms.DateInput(attrs={'type':'date'}))
  end_date              = forms.DateField(label='End of range',
                            required=False,
                            widget=forms.DateInput(attrs={'type':'date'}))
  repeat_each           = forms.IntegerField(label='Repeat',
                            required=False)
  criteria              = forms.CharField(label='Criteria',
                            help_text='<span id="criteria_help_text">&nbsp;</span>',
                            required=False)

  title                 = forms.CharField(label='Title',
                            required=False)
  club_global           = forms.BooleanField(label='Club',
                            required=False)
  start_time            = forms.TimeField(label='Time',
                            required=False,
                            widget=forms.TimeInput(attrs={'type':'time'}))
  duration              = SimpleDurationField(label='Duration',
                            help_text='<i>[D days,] hh:mm</i>',
                            required=False)
  all_day               = forms.BooleanField(label='All day?',
                            required=False)

  def __init__(self, event_type_choices=None, *args, **kwargs):
    super(EventEditForm, self).__init__(*args, **kwargs)
    self.fields['event_type'].choices = event_type_choices

  def current_event_type_choices(self):
    return self.fields['event_type'].choices

  def clean(self):
    super(EventEditForm, self).clean()

    # Some fields are always required, but we handle the validation here for consistency

    if not self.cleaned_data.get('title'):
      self.add_error('title', "This field is required.")

    start_date = self.cleaned_data.get('start_date')
    if start_date is None:
      self.add_error('start_date', "This field is required.")

    if self.cleaned_data.get('duration') is None:
      self.add_error('duration', "This field is required.")

    # Other fields require special handling

    if self.cleaned_data.get('all_day'):
      self.cleaned_data['start_time'] = None
    else:
      if self.cleaned_data.get('start_time') is None:
        self.add_error('start_time', "This field is required.")

    event_type = self.cleaned_data.get('event_type')
    if event_type != self.NORECURRING:
      end_date = self.cleaned_data.get('end_date')
      if end_date is None:
        self.add_error('end_date', "This field is required.")
      elif (not start_date is None) and (end_date < start_date):
        self.add_error('end_date', "May not be less than Start Date.")

      repeat_each = self.cleaned_data.get('repeat_each')
      if repeat_each is None:
        self.add_error('repeat_each', "This field is required.")
      elif repeat_each < 1:
        self.add_error('repeat_each', "Must be at least 1.")

      criteria = self.cleaned_data.get('criteria')
      if event_type == RecurringEvent.WEEKLY:
        if criteria:
          criteria = criteria.replace(' ','').lower()
          if bool(re_weekly.search(criteria + ',')):
            self.cleaned_data['criteria'] = criteria
          else:
            self.add_error('criteria', "Criteria is not in the proper format for weekly events.")
        else:
          self.add_error('criteria', "Weekly events must specify a criteria string.")

      elif event_type == RecurringEvent.MONTHLY:
        if criteria:
          criteria = criteria.replace(' ','').lower()
          if bool(re_monthly.search(criteria + ',')):
            self.cleaned_data['criteria'] = criteria
          else:
            self.add_error('criteria', "Criteria is not in the proper format for monthly events.")
        else:
          self.add_error('criteria', "Monthly events must specify a criteria string.")

src/templates/infosec/about_contact.html
{% extends "base.html" %}
{% load staticfiles crispy_forms_tags contentblock_renderer %}

{% block title %}Contact Us{% endblock %}

{% block content %}
<h1>Contact Us</h1>

{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }}" role="alert">{{ message }}</div>
{% endfor %}
{% endif %}

<div class="row">
  <div class="col-sm-7">
    <p>Please use the form below to send any suggestions, questions, or complaints to the club's primary email:</p>
    <form method="POST">{% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-default" type="submit" value="Submit">
    </form>
  </div>
  <div class="col-sm-5">
    <p>If instead you would like to contact a club officer directly, see the list below:</p>
    {% load_contentblock 'about_part1' %}
  </div>
</div>
{% endblock %}

src/templates/infosec/contentblock_view.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{{title}}{% endblock %}

{% block content %}
  {% if messages %}
  {% for message in messages %}
  <div class="alert {{ message.tags }}" role="alert">{{ message }}</div>
  {% endfor %}
  {% endif %}

  {{ renderedblob|safe }}
{% endblock %}

src/templates/infosec/events_edit.html
{% extends "base.html" %}
{% load sekizai_tags staticfiles crispy_forms_tags events_formatting %}

{% block outertitle %}{% if addmode %}New Event{% else %}Edit Event{% endif %}{% endblock %}

{% block content %}
{% addtoblock "css" %}
  <link rel='stylesheet' href="{% static 'csstoggle/toggle-switch.css' %}">
  <link rel='stylesheet' href="{% static 'infosec/events_edit.css' %}">
  <style>
  {% if initial_event_type == 0 %}
  .hide-if-onetime {display:none}
  {% else %}
  .show-if-onetime {display:none}
  {% endif %}
  </style>
{% endaddtoblock %}
{% addtoblock "js" %}
  <script type="text/javascript">
  var coll_hideifonetime, coll_showifonetime;
  var event_type_selector;
  var div_id_start_date, start_date_parent_if_onetime, start_date_parent_if_recurring;
  var id_criteria, criteria_help_text;
  var id_all_day, id_start_time, id_duration;
  function on_event_type_change(et) {
    if (et=={{form.NORECURRING}}) {   // One-time event
      coll_hideifonetime.hide();
      coll_showifonetime.show();

      // Change color of Event Type slider
      event_type_selector.removeClass("progress-bar-warning").addClass("progress-bar-info");

      // Move the date field
      div_id_start_date.prependTo(start_date_parent_if_onetime)

    }else{                            // Recurring event
      var ws = [750,600];
      iw = ws[0]-window.innerWidth; if (iw<0) {iw=0;}
      ih = ws[1]-window.innerHeight; if (ih<0) {ih=0;}
      if ((iw>0) || (ih>0)) {window.resizeBy(iw,ih);}

      coll_showifonetime.hide();
      coll_hideifonetime.show();

      // Change color of Event Type slider
      event_type_selector.removeClass("progress-bar-info").addClass("progress-bar-warning");

      // Move the date field
      div_id_start_date.prependTo(start_date_parent_if_recurring)

      // Disable the criteria field for Daily events only
      if (et==100) {
        id_criteria.prop("disabled", "true");
      }else{
        id_criteria.prop("disabled", "");
      }

      // Update help_text for the criteria field
      if (false) {
      {% for et_id,et_help in form.criteria_help_texts %}
      }else if (et=={{et_id}}) {
        criteria_help_text.html('{{et_help|safe}}');
      {% endfor %}
      }
    }
  }
  function on_all_day_change(e) {
    if (id_all_day.prop("checked") === true) {
      id_start_time.val('').prop("disabled", "true");
      if (e) id_duration.val('1 day');
    }else{
      id_start_time.prop("disabled", "");
    }
  }
  $(function() {
    // Preload the elements we'll be working with
    coll_hideifonetime = $('.hide-if-onetime'); coll_showifonetime = $('.show-if-onetime');
    event_type_selector = $('#event_type_selector');
    div_id_start_date = $('#div_id_start_date'); start_date_parent_if_onetime = $('#start_date_parent_if_onetime'); start_date_parent_if_recurring = $('#start_date_parent_if_recurring');
    id_criteria = $('#id_criteria'); criteria_help_text = $('#criteria_help_text');
    id_all_day = $('#id_all_day'); id_start_time = $('#id_start_time'); id_duration = $('#id_duration');

    // Initialize the Rule Type switch
    $('#id_event_type_' + {{initial_event_type}}).prop('checked', true);
    on_event_type_change({{initial_event_type}});

    // Initialize the All Day switch
    on_all_day_change(false);

    {% if show_events_preview %}
    // Scroll to the preview of events
    $(document.body).animate({
      scrollTop: document.getElementById('events_preview').getBoundingClientRect().top + document.body.scrollTop - 10
    }, 500);
    {% else %}
    // Set initial focus
    $('#id_title').focus();
    {% endif %}
  })

  </script>
{% endaddtoblock %}

{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }}" role="alert">{{ message }}</div>
{% endfor %}
{% endif %}

<form id="mainform" action="{% if addmode %}{% url 'newevent' %}{% elif initial_event_type == 0 %}{% url 'editevent' eventid %}{% else %}{% url 'editrecurringevent' eventid %}{% endif %}" method="post">
  {% csrf_token %}

  <label class="control-label">{{ form.event_type.label|safe }}</label>
  <div class="switch-toggle well progress-striped">
    {% if form.current_event_type_choices|length > 1 %}
      {% for et_id,et_name in form.current_event_type_choices %}
      <input {% if initial_event_type == et_id %}checked {% endif %}id="id_event_type_{{et_id}}" name="event_type" value="{{et_id}}" type="radio" onclick="on_event_type_change({{et_id}})">
      <label for="id_event_type_{{et_id}}">{{et_name}}</label>
      {% endfor %}
      <a id="event_type_selector" class="progress-bar {% if initial_event_type != 0 %}progress-bar-warning{% else %}progress-bar-info{% endif %}"></a>
    {% else %}
      {% for et_id,et_name in form.current_event_type_choices %}
      <input checked id="id_event_type_{{et_id}}" name="event_type" value="{{et_id}}" type="radio">
      <label for="id_event_type_{{et_id}}" style="width:100%">{{et_name}}</label>
      {% endfor %}
      <a id="event_type_selector" style="width:100%" class="progress-bar {% if initial_event_type != 0 %}progress-bar-warning{% else %}progress-bar-info{% endif %}"></a>
    {% endif %}
  </div>

  {% if original_event_id %}
    <div class="top-msg">Did you mean to <a class="alert-link" href="{% url 'editevent' original_event_id %}?noredir=1">edit the individual event</a> instead?</div>
  {% endif %}
  {% if linked_recurringevent_id %}
    <div class="top-msg">This event is part of a recurring series. Would you like to <a class="alert-link" href="{% url 'editrecurringevent' linked_recurringevent_id eventid %}">edit that instead</a>?</div>
  {% endif %}

  <div class="well hide-if-onetime" style="padding-bottom:0px;">
    <div class="row">
      <div class="col-xs-5" id="start_date_parent_if_recurring">{% if initial_event_type != 0 %}{{ form.start_date|as_crispy_field }}{% endif %}</div>
      <div class="col-xs-5">{{ form.end_date|as_crispy_field }}</div>
      <div class="col-xs-2">{{ form.repeat_each|as_crispy_field }}</div>
    </div>

    {{ form.criteria|as_crispy_field }}
  </div>

  <div class="row">
    <div class="col-xs-9">{{ form.title|as_crispy_field }}</div>
    <div class="col-xs-3">
      <label for="id_club_global" class="control-label">{{ form.club_global.label|safe }}</label>
      <label class="switch-light">
        <input {% if form.club_global.value == True %}checked {% endif %}class="checkboxinput" id="id_club_global" name="club_global" type="checkbox">
        <span class="well">
          <span>{{current_club_shortname}}</span>
          <span>Global</span>
          <a class="btn btn-info"></a>
        </span>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-3" id="start_date_parent_if_onetime">
      {% if initial_event_type == 0 %}{{ form.start_date|as_crispy_field }}{% endif %}
      <div class="form-group hide-if-onetime">
        <label class="control-label">Date</label>
        <div class="controls"><input class="dateinput form-control" value="see criteria above" disabled style="font-size:11px; font-style:italic;"></div>
      </div>
    </div>
    <div class="col-xs-3">{{ form.start_time|as_crispy_field }}</div>
    <div class="col-xs-3">{{ form.duration|as_crispy_field }}</div>
    <div class="col-xs-3">
      <label for="id_all_day" class="control-label">{{ form.all_day.label|safe }}</label>
      <label class="switch-light">
        <input {% if form.all_day.value == True %}checked {% endif %}class="checkboxinput" id="id_all_day" name="all_day" type="checkbox" onclick="on_all_day_change(true)">
        <span class="well">
          <span>Timed</span>
          <span>All day</span>
          <a class="btn btn-info"></a>
        </span>
      </label>
    </div>
  </div>

  <div class="hide-if-onetime">
    {% if show_events_preview %}
    <div class="panel panel-primary" id="events_preview">
      <div class="panel-heading">Preview of recurring events to be added/changed/deleted</div>
      <table class="table">
        <thead><tr><th>ID</th><th>Date/Time</th><th>Duration</th><th>All day?</th><th>Action</th></tr></thead>
        <tbody>
        {% for event in events %}
        <tr class="{{ event.class }}"><td>{{event.id|eventid}}</td><td>{{ event.start|eventdate:event.all_day }}</td><td>{{event.duration}}</td><td>{% if event.all_day %}All day{% endif %}</td><td>{{event.action}}</td></tr>
        {% empty %}
        <tr><td colspan="5">No events match the criteria.</td></tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <br>
    <br>
    <br>
    {% endif %}
  </div>

  <div class="form-actions">
    {% if addmode %}
      <input type="submit" name="_submitpreview" value="Preview Recurring Events" class="btn btn-default hide-if-onetime">
      <input type="submit" name="_submitsave" value="Save" class="btn btn-primary">
    {% else %}
      {% if initial_event_type == 0 %}
      <input type="submit" name="_submitsave" value="Save" class="btn btn-primary">
      <input type="submit" name="_submitdelete" value="Delete" class="btn btn-danger">
      {% else %}
      <input type="submit" name="_submitpreview" value="Preview Changes" class="btn btn-default">
      <input type="submit" name="_submitsave" value="Apply Changes" class="btn btn-primary">
      <input type="submit" name="_submitdelete" value="Delete Series" class="btn btn-danger">
      {% endif %}
    {% endif %}
  </div>
</form>
{% endblock %}

src/templates/infosec/events_editform.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{% if add %}New Event{% else %}Edit Event{% endif %}{% endblock %}

{% block extrahead %}
<script type="text/javascript">
$(function() {
  $('#id_title').focus();
})
</script>
{% endblock %}

{% block content %}
{% if add %}
<form  action="/events/new/" method="post" >
{% else %}
<form  action="/events/edit/{{eventid}}/" method="post" >
{% endif %}
{% csrf_token %}
{{ form|crispy }}
<div class="form-actions">
  {% if add %}
  <input type="submit" name="_submitadd" value="Add" class="btn btn-primary" id="submit-id-action">
  {% else %}
  <input type="submit" name="_submitsave" value="Save" class="btn btn-primary" id="submit-id-action">
  <input type="submit" name="_submitdelete" value="Delete" class="btn btn-danger test" id="submit-id-action">
  {% endif %}
</div>
</form>
{% endblock %}